# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: golem15.user::lang.user.label

# Model Form Field configuration
form: $/golem15/user/models/user/fields.yaml

# Model Class name
modelClass: Golem15\User\Models\User

# Default redirect location
defaultRedirect: golem15/user/users

# Create page
create:
    redirect: golem15/user/users/preview/:id
    redirectClose: golem15/user/users

# Update page
update:
    redirect: golem15/user/users/update/:id
    redirectClose: golem15/user/users/preview/:id
