<?php

namespace Golem15\User\Classes;

use Lang;
use Illuminate\Support\Facades\Mail;
use Golem15\User\Models\User as UserModel;

/**
 * Mail glue for CR-01's password-bootstrap confirmation flow, shared by
 * ApiController::changePassword() and the mirrored Account::onUpdate() CMS path so the
 * two call sites never drift (same pattern as the has_self_set_password predicate
 * itself -- one place to audit).
 *
 * Both sends are best-effort / degrade-safe: `Mail::queue()` failing (a broken mail
 * transport, not merely an unconfigured one -- the default `log`/`array` drivers never
 * throw) must never silently grant the relaxed write it is supposed to gate, and must
 * never permanently strand the caller either. The pre-existing, always-available
 * `/forgot-password` -> `/reset-password` flow (untouched by this change) is the
 * documented fallback -- see 14-REVIEW.md CR-01 resolution notes.
 */
class PasswordBootstrapMailer
{
    /**
     * Send the confirmation code the caller must echo back before the relaxed
     * (no-current-password) write is allowed to commit.
     *
     * @param UserModel $user
     * @param string $code Plaintext code (already generated by
     *                     User::issuePasswordBootstrapCode() -- never re-derived here).
     * @return bool True if the mail was successfully queued.
     */
    public static function sendConfirmationCode(UserModel $user, string $code): bool
    {
        try {
            Mail::queue('golem15.user::mail.password_bootstrap_code', [
                'name' => $user->name,
                'code' => $code,
                'ttl_minutes' => UserModel::PASSWORD_BOOTSTRAP_CODE_TTL_MINUTES,
            ], function ($message) use ($user) {
                $message->to($user->email, $user->full_name);
            });

            return true;
        } catch (\Throwable $e) {
            \Log::error('Failed to queue password-bootstrap confirmation code email', [
                'user_id' => $user->id,
                'error' => $e->getMessage(),
            ]);

            return false;
        }
    }

    /**
     * Defence-in-depth (14-REVIEW.md CR-01, item (d)): notify the account's own email
     * every time a password change actually commits via the relaxed path, independent
     * of whether the confirmation-code step above succeeded to deliver -- so the
     * legitimate owner has a paper trail even if this specific mail bounces later.
     * Best-effort: a failure here must never undo an already-committed, already
     * confirmed password change.
     *
     * @param UserModel $user
     * @return bool True if the mail was successfully queued.
     */
    public static function sendSecurityNotification(UserModel $user): bool
    {
        try {
            Mail::queue('golem15.user::mail.security_password_changed', [
                'name' => $user->name,
            ], function ($message) use ($user) {
                $message->to($user->email, $user->full_name);
            });

            return true;
        } catch (\Throwable $e) {
            \Log::error('Failed to queue password-changed security notification email', [
                'user_id' => $user->id,
                'error' => $e->getMessage(),
            ]);

            return false;
        }
    }
}
